<!DOCTYPE html>
<!--[if IE 8]> <html lang="ko" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="ko" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="ko">
<!--<![endif]-->

<head>
	<title>KINCOWEB STD</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
	<!--[if lte IE 8]><script src="/website/assets/js/ie/html5shiv.js"></script><![endif]-->
	<link rel="stylesheet" href="/website/assets/css/main.css" />
	<!--[if lte IE 9]><link rel="stylesheet" href="/website/assets/css/ie9.css" /><![endif]-->
	<!--[if lte IE 8]><link rel="stylesheet" href="/website/assets/css/ie8.css" /><![endif]-->
</head>

<body>

	<!-- Header -->
	<header id="header">
		<a href="/website/index.html" class="title">KINCOWEB STD</a>
		<nav>
			<ul>
				<li>
					<a href="/website/java/index.html">Java</a>
				</li>
				<li>
					<a href="Exception.html">Exception</a>
				</li>
				<li>
					<a class="active">예외 되던지기</a>
				</li>
			</ul>
		</nav>
	</header>

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
		<section id="main" class="wrapper">
			<div class="inner">
				<h1 class="major">예외 되던지기</h1>

				<section>
					<h2>예외 되던지기 (exception re-throwing)</h2>
					<p>
						한 메소드에서 발생할 수 있는
						<strong>예외가 여럿인 경우</strong>, 몇 개는 try-catch문을 통해서 메소드 내에서 자체적으로 처리하고, 그 나머지는 선언부에 지정하여 호출한 메소드에서 처리하도록 함으로써 양쪽에서
						<strong>예외를 나누어 처리</strong>되도록 할 수 있습니다.
						<br/>또는
						<strong>단 하나의 예외에 대해서도 예외가 발생한 메소드와 호출한 메소드 양쪽에서 처리</strong>하도록 할 수도 있습니다.
						<br/>이것은
						<strong>예외를 처리한 후에 인위적으로 다시 발생시키는 방법을 통해서 가능하도록 구현</strong>하는데 이것을
						<strong>예외 되던지기(exception re-throwing)</strong> 이라고 합니다.
					</p>
					<h4>ExceptionEx14.java</h4>
					<pre><code>package kinco.java.std;

public class ExceptionEx14 {
	public static void main(String[] args) {
		try {
			myMethod();
		} catch (Exception e) {
			System.out.println("main메서드에서 예외가 처리되었습니다.");
		}
	}

	private static void myMethod() throws Exception {
		try {
			throw new Exception();
		} catch (Exception e) {
			System.out.println("myMethod메서드에서 예외가 처리되었습니다.");
			throw e; // 다시 예외를 발생
		}
	}
}</code></pre>

					<h4>Console</h4>
					<pre><code>myMethod메서드에서 예외가 처리되었습니다.
main메서드에서 예외가 처리되었습니다.</code></pre>

					<p>
						예외가 발생할 가능성이 있는 메소드에 try-catch문을 사용해서 예외를 처리해주고 catch문에서 필요한 작업을 행한 후에 throw문을 사용해서 예외를 다시 발생시킵니다.
						<br/>다시 발생한 예외는 이 메소드를 호출한 메소드에게 전달되고 호출한 메소드의 try-catch문에서 다시 예외를 처리합니다.
						<br/>만약 <strong>반환값이 void가 아닌 경우</strong>라면 <code>catch문</code>에도 <code>return문</code>이 있어야 합니다. <strong>예외가 발생했을 경우에도 값을 반환</strong>해야
						하기 때문입니다.
					</p>
				</section>

				<hr/>

				<section>
					<ul class="actions fit">
						<li>
							<a href="Exception_05.html" class="button fit">자동 자원 반환</a>
						</li>
						<li></li>
						<li>
							<a href="Exception_07.html" class="button fit">연결된 예외</a>
						</li>
					</ul>
				</section>
			</div>
		</section>
	</div>

	<!-- Footer -->
	<footer id="footer" class="wrapper alt">
		<div class="inner">
			<ul class="menu">
				<li>&copy; KimYong. All rights reserved.</li>
				<li>KINCOWEB:
					<a href="#">KincoWeb Std.</a>
				</li>
			</ul>
		</div>
	</footer>

	<!-- Scripts -->
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="/website/assets/js/jquery.scrollex.min.js"></script>
	<script src="/website/assets/js/jquery.scrolly.min.js"></script>
	<script src="/website/assets/js/skel.min.js"></script>
	<script src="/website/assets/js/util.js"></script>
	<!--[if lte IE 8]><script src="/website/assets/js/ie/respond.min.js"></script><![endif]-->
	<script src="/website/assets/js/main.js"></script>

</body>

</html>